# cmpp 客户端配置
[cmpp_client]
key = "client"
version = "V30"
read_timeout = 1
active_test_interval = 60
max_no_resp_pkg_num = 3
enable = true
[[cmpp_client.accounts]]
ip = "127.0.0.1"
port = 7890
username = ""
password = ""
sp_id = ""
sp_code = ""

# 发送短信内容配置
[[cmpp_client.messages]]
# 扩展码
extend = ""
content = "【Test】领取属于您的优惠。回T退订"
phone = "12345678901"

# cmpp 服务端配置
[cmpp_server]
ip = "127.0.0.1"
port = 7890
enable = true
version = "V30"
deliver_interval = 5
# 心跳检测时间
heartbeat = 1
# 无响应时发送最大包个数
max_no_resp_pkgs = 3
[[cmpp_server.auths]]
username = "test"
password = "test123"
sp_id = ""
sp_code = ""

# 压测配置
[stress_test]
concurrency = 1000
duration_time = 120
total_num = 10000

# 日志配置
[log]
dir = "./log"
file = "mock-cmpp-stress-test.log"
level = "info"
local_time = true

# redis配置
[redis]
ip = "127.0.0.1"
port = 3306
db = 0
password = ""
timeout = 300
wait = true
enable = false
clear_key = false